# Generated by Django 4.2.11 on 2026-03-10 04:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('tenants', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock', models.IntegerField(default=0)),
                ('status', models.CharField(db_index=True, default='active', max_length=20)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.shop')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['shop_id', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='ProductDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(db_index=True)),
                ('units_sold', models.PositiveIntegerField(default=0)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cost_of_goods', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('ads_spend', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('booking_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('livestream_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('profit_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('roas_estimate', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='products.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_daily_stats', to='shops.shop')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-stat_date', 'shop_id', 'product_id'],
                'indexes': [models.Index(fields=['tenant', 'shop', 'stat_date'], name='pds_t_sh_dt_idx'), models.Index(fields=['tenant', 'product', 'stat_date'], name='pds_t_pd_dt_idx'), models.Index(fields=['tenant', 'stat_date'], name='pds_t_dt_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='productdailystat',
            constraint=models.UniqueConstraint(fields=('shop', 'product', 'stat_date'), name='uq_shop_product_stat_date'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'shop'], name='products_pr_tenant__cf73cf_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'sku'], name='products_pr_tenant__832bf8_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('shop', 'sku'), name='uq_shop_sku'),
        ),
    ]
