# Generated by Django 4.2.11 on 2026-03-12 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default='', max_length=255)),
                ('module_code', models.CharField(choices=[('custom', 'Custom'), ('work', 'Work'), ('contract', 'Contract'), ('content', 'Content'), ('finance', 'Finance'), ('booking', 'Booking')], db_index=True, default='custom', max_length=50)),
                ('linked_target_type', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('linked_target_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sheets_sheet',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='SheetRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet_rows_created', to=settings.AUTH_USER_MODEL)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='sheets.sheet')),
            ],
            options={
                'db_table': 'sheets_sheet_row',
                'ordering': ('position', 'id'),
                'unique_together': {('sheet', 'position')},
            },
        ),
        migrations.CreateModel(
            name='SheetColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.SlugField(blank=True, default='', max_length=255)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select')], default='text', max_length=20)),
                ('position', models.IntegerField(db_index=True, default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='sheets.sheet')),
            ],
            options={
                'db_table': 'sheets_sheet_column',
                'ordering': ('position', 'id'),
                'unique_together': {('sheet', 'position')},
            },
        ),
        migrations.CreateModel(
            name='SheetCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='sheets.sheetcolumn')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='sheets.sheetrow')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet_cells_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sheets_sheet_cell',
                'unique_together': {('row', 'column')},
            },
        ),
        migrations.AddIndex(
            model_name='sheet',
            index=models.Index(fields=['tenant_id', 'module_code'], name='sheets_shee_tenant__2146ee_idx'),
        ),
        migrations.AddIndex(
            model_name='sheet',
            index=models.Index(fields=['tenant_id', 'linked_target_type', 'linked_target_id'], name='sheets_shee_tenant__c9197f_idx'),
        ),
    ]
