# Generated by Django 4.2.11 on 2026-03-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetcolumn',
            name='data_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('image', 'Image')], default='text', max_length=20),
        ),
    ]
