# Generated by Django 4.2.11 on 2026-03-04 17:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0010_remove_shopmember_uq_shopmember_shop_user_and_more'),
        ('companies', '0004_alter_company_unique_together_and_more'),
        ('tenants', '0009_tenant_suspended_at_alter_tenant_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('version', models.PositiveIntegerField(db_index=True, default=1)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, default='', max_length=180)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='new', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.shop')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'available_at', 'id'], name='obx_st_av_id_idx'), models.Index(fields=['tenant', 'name', 'created_at'], name='obx_t_nm_ct_idx'), models.Index(fields=['dedupe_key'], name='obx_dedupe_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='outboxevent',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('dedupe_key',), name='uq_outbox_dedupe_key'),
        ),
    ]
