# Generated by Django 4.2.11 on 2026-03-10 04:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('tenants', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=120)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('contract_type', models.CharField(choices=[('booking', 'Booking KOC/KOL'), ('channel', 'Xây kênh'), ('operation', 'Vận hành')], db_index=True, default='operation', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('active', 'Đang hiệu lực'), ('paused', 'Tạm dừng'), ('done', 'Hoàn thành'), ('cancelled', 'Huỷ')], db_index=True, default='draft', max_length=20)),
                ('partner_name', models.CharField(blank=True, default='', max_length=255)),
                ('signed_at', models.DateField(blank=True, db_index=True, null=True)),
                ('start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('note', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='companies.company')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ContractChannelContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('script_text', models.TextField(blank=True, default='')),
                ('content_pillar', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('idea', 'Ý tưởng'), ('script', 'Đã có kịch bản'), ('pre_production', 'Chuẩn bị quay'), ('production', 'Đang sản xuất'), ('post_production', 'Hậu kỳ'), ('scheduled', 'Đã lên lịch'), ('aired', 'Đã air'), ('cancelled', 'Huỷ')], db_index=True, default='idea', max_length=30)),
                ('planned_publish_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('aired_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('video_link', models.URLField(blank=True, default='')),
                ('visible_to_client', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=1)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_contents', to='contracts.contract')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_channel_contents', to='shops.shop')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContractMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('kind', models.CharField(choices=[('kpi', 'KPI'), ('acceptance', 'Nghiệm thu'), ('delivery', 'Bàn giao'), ('payment_condition', 'Điều kiện thanh toán'), ('other', 'Khác')], db_index=True, default='other', max_length=30)),
                ('status', models.CharField(choices=[('todo', 'Chưa xử lý'), ('doing', 'Đang xử lý'), ('done', 'Hoàn thành'), ('cancelled', 'Huỷ')], db_index=True, default='todo', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=1)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='contracts.contract')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.shop')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContractPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Số tiền gốc trước VAT', max_digits=18)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=0, help_text='Phần trăm VAT áp dụng cho dòng thanh toán này', max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, help_text='Tiền VAT của dòng thanh toán này', max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Tổng tiền phải thanh toán = amount + vat_amount', max_digits=18)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('partial', 'Thanh toán một phần'), ('paid', 'Đã thanh toán'), ('overdue', 'Quá hạn'), ('cancelled', 'Huỷ')], db_index=True, default='pending', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.contract')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='contracts.contractmilestone')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['due_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContractChannelInsightSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_score', models.PositiveIntegerField(db_index=True, default=0)),
                ('ai_label', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('ai_recommendation', models.TextField(blank=True, default='')),
                ('priority_score', models.PositiveIntegerField(db_index=True, default=0)),
                ('priority_label', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('priority_reason', models.TextField(blank=True, default='')),
                ('action_hint', models.TextField(blank=True, default='')),
                ('views_14d', models.PositiveIntegerField(default=0)),
                ('orders_14d', models.PositiveIntegerField(default=0)),
                ('revenue_14d', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('computed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_snapshots', to='contracts.contractchannelcontent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-computed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContractChannelDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField(db_index=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('saves', models.PositiveIntegerField(default=0)),
                ('orders', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='contracts.contractchannelcontent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-metric_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContractBookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koc_name', models.CharField(db_index=True, max_length=255)),
                ('koc_channel_name', models.CharField(blank=True, default='', max_length=255)),
                ('koc_channel_link', models.URLField(blank=True, default='')),
                ('booking_type', models.CharField(choices=[('free_cast', 'Free cast / đơn giá cố định'), ('percent_deal', '% giá trị hợp đồng')], db_index=True, default='free_cast', max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('expected_post_count', models.PositiveIntegerField(default=1)),
                ('delivered_post_count', models.PositiveIntegerField(default=0)),
                ('brand_amount', models.DecimalField(decimal_places=2, default=0, help_text='Số tiền nhãn hàng / khách thanh toán cho deal này nếu cần theo dõi riêng', max_digits=18)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0, help_text='Số tiền phải thanh toán cho KOC', max_digits=18)),
                ('air_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('video_link', models.URLField(blank=True, default='')),
                ('payout_due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('payout_paid_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('payout_status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('cancelled', 'Huỷ')], db_index=True, default='pending', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_items', to='contracts.contract')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.shop')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ContractShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_shops', to='contracts.contract')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_contracts', to='shops.shop')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['tenant', 'contract'], name='cshop_t_ct_idx'), models.Index(fields=['tenant', 'shop'], name='cshop_t_sh_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='contractshop',
            constraint=models.UniqueConstraint(fields=('contract', 'shop'), name='uq_contract_shop'),
        ),
        migrations.AddIndex(
            model_name='contractpayment',
            index=models.Index(fields=['tenant', 'contract', 'status'], name='cp_t_ct_st_idx'),
        ),
        migrations.AddIndex(
            model_name='contractpayment',
            index=models.Index(fields=['tenant', 'due_at', 'status'], name='cp_t_due_st_idx'),
        ),
        migrations.AddIndex(
            model_name='contractmilestone',
            index=models.Index(fields=['tenant', 'contract', 'status'], name='cms_t_ct_st_idx'),
        ),
        migrations.AddIndex(
            model_name='contractmilestone',
            index=models.Index(fields=['tenant', 'due_at', 'status'], name='cms_t_due_st_idx'),
        ),
        migrations.AddIndex(
            model_name='contractmilestone',
            index=models.Index(fields=['tenant', 'shop', 'status'], name='cms_t_sh_st_idx'),
        ),
        migrations.AddIndex(
            model_name='contractchannelinsightsnapshot',
            index=models.Index(fields=['tenant', 'content', 'computed_at'], name='ccis_t_ct_cmp_idx'),
        ),
        migrations.AddIndex(
            model_name='contractchannelinsightsnapshot',
            index=models.Index(fields=['tenant', 'priority_label', 'computed_at'], name='ccis_t_pl_cmp_idx'),
        ),
        migrations.AddIndex(
            model_name='contractchannelinsightsnapshot',
            index=models.Index(fields=['tenant', 'ai_label', 'computed_at'], name='ccis_t_al_cmp_idx'),
        ),
        migrations.AddIndex(
            model_name='contractchanneldailymetric',
            index=models.Index(fields=['tenant', 'content', 'metric_date'], name='ccdm_t_ct_dt_idx'),
        ),
        migrations.AddConstraint(
            model_name='contractchanneldailymetric',
            constraint=models.UniqueConstraint(fields=('content', 'metric_date'), name='uq_channel_content_metric_date'),
        ),
        migrations.AddIndex(
            model_name='contractchannelcontent',
            index=models.Index(fields=['tenant', 'contract', 'status'], name='ccc_t_ct_st_idx'),
        ),
        migrations.AddIndex(
            model_name='contractchannelcontent',
            index=models.Index(fields=['tenant', 'shop', 'status'], name='ccc_t_sh_st_idx'),
        ),
        migrations.AddIndex(
            model_name='contractchannelcontent',
            index=models.Index(fields=['tenant', 'visible_to_client'], name='ccc_t_vtc_idx'),
        ),
        migrations.AddIndex(
            model_name='contractchannelcontent',
            index=models.Index(fields=['tenant', 'aired_at'], name='ccc_t_air_idx'),
        ),
        migrations.AddIndex(
            model_name='contractbookingitem',
            index=models.Index(fields=['tenant', 'contract'], name='cbi_t_ct_idx'),
        ),
        migrations.AddIndex(
            model_name='contractbookingitem',
            index=models.Index(fields=['tenant', 'shop'], name='cbi_t_sh_idx'),
        ),
        migrations.AddIndex(
            model_name='contractbookingitem',
            index=models.Index(fields=['tenant', 'air_date'], name='cbi_t_air_idx'),
        ),
        migrations.AddIndex(
            model_name='contractbookingitem',
            index=models.Index(fields=['tenant', 'payout_due_at', 'payout_status'], name='cbi_t_paydue_st_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant', 'contract_type', 'status'], name='ct_t_tp_st_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant', 'company', 'status'], name='ct_t_co_st_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant', 'start_date', 'end_date'], name='ct_t_sd_ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_contract_tenant_code'),
        ),
    ]
