# Generated by Django 4.2.11 on 2026-03-08 05:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0009_tenant_suspended_at_alter_tenant_status_and_more'),
        ('companies', '0004_alter_company_unique_together_and_more'),
        ('shops', '0010_remove_shopmember_uq_shopmember_shop_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=120)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('contract_type', models.CharField(choices=[('booking', 'Booking KOC/KOL'), ('channel', 'Xây kênh'), ('operation', 'Vận hành')], db_index=True, default='operation', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('active', 'Đang hiệu lực'), ('paused', 'Tạm dừng'), ('done', 'Hoàn thành'), ('cancelled', 'Huỷ')], db_index=True, default='draft', max_length=20)),
                ('partner_name', models.CharField(blank=True, default='', max_length=255)),
                ('signed_at', models.DateField(blank=True, db_index=True, null=True)),
                ('start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('note', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='companies.company')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ContractMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('kind', models.CharField(choices=[('kpi', 'KPI'), ('acceptance', 'Nghiệm thu'), ('delivery', 'Bàn giao'), ('payment_condition', 'Điều kiện thanh toán'), ('other', 'Khác')], db_index=True, default='other', max_length=30)),
                ('status', models.CharField(choices=[('todo', 'Chưa xử lý'), ('doing', 'Đang xử lý'), ('done', 'Hoàn thành'), ('cancelled', 'Huỷ')], db_index=True, default='todo', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=1)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='contracts.contract')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.shop')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContractPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('partial', 'Thanh toán một phần'), ('paid', 'Đã thanh toán'), ('overdue', 'Quá hạn'), ('cancelled', 'Huỷ')], db_index=True, default='pending', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.contract')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='contracts.contractmilestone')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['due_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContractBookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koc_name', models.CharField(db_index=True, max_length=255)),
                ('koc_channel_name', models.CharField(blank=True, default='', max_length=255)),
                ('koc_channel_link', models.URLField(blank=True, default='')),
                ('booking_type', models.CharField(choices=[('free_cast', 'Free cast / đơn giá cố định'), ('percent_deal', '% giá trị hợp đồng')], db_index=True, default='free_cast', max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('expected_post_count', models.PositiveIntegerField(default=1)),
                ('delivered_post_count', models.PositiveIntegerField(default=0)),
                ('brand_amount', models.DecimalField(decimal_places=2, default=0, help_text='Số tiền nhãn hàng / khách thanh toán cho deal này nếu cần theo dõi riêng', max_digits=18)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0, help_text='Số tiền phải thanh toán cho KOC', max_digits=18)),
                ('air_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('video_link', models.URLField(blank=True, default='')),
                ('payout_due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('payout_paid_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('payout_status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('cancelled', 'Huỷ')], db_index=True, default='pending', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_items', to='contracts.contract')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.shop')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ContractShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_shops', to='contracts.contract')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_contracts', to='shops.shop')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['tenant', 'contract'], name='cshop_t_ct_idx'), models.Index(fields=['tenant', 'shop'], name='cshop_t_sh_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='contractshop',
            constraint=models.UniqueConstraint(fields=('contract', 'shop'), name='uq_contract_shop'),
        ),
        migrations.AddIndex(
            model_name='contractpayment',
            index=models.Index(fields=['tenant', 'contract', 'status'], name='cp_t_ct_st_idx'),
        ),
        migrations.AddIndex(
            model_name='contractpayment',
            index=models.Index(fields=['tenant', 'due_at', 'status'], name='cp_t_due_st_idx'),
        ),
        migrations.AddIndex(
            model_name='contractmilestone',
            index=models.Index(fields=['tenant', 'contract', 'status'], name='cms_t_ct_st_idx'),
        ),
        migrations.AddIndex(
            model_name='contractmilestone',
            index=models.Index(fields=['tenant', 'due_at', 'status'], name='cms_t_due_st_idx'),
        ),
        migrations.AddIndex(
            model_name='contractmilestone',
            index=models.Index(fields=['tenant', 'shop', 'status'], name='cms_t_sh_st_idx'),
        ),
        migrations.AddIndex(
            model_name='contractbookingitem',
            index=models.Index(fields=['tenant', 'contract'], name='cbi_t_ct_idx'),
        ),
        migrations.AddIndex(
            model_name='contractbookingitem',
            index=models.Index(fields=['tenant', 'shop'], name='cbi_t_sh_idx'),
        ),
        migrations.AddIndex(
            model_name='contractbookingitem',
            index=models.Index(fields=['tenant', 'air_date'], name='cbi_t_air_idx'),
        ),
        migrations.AddIndex(
            model_name='contractbookingitem',
            index=models.Index(fields=['tenant', 'payout_due_at', 'payout_status'], name='cbi_t_paydue_st_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant', 'contract_type', 'status'], name='ct_t_tp_st_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant', 'company', 'status'], name='ct_t_co_st_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant', 'start_date', 'end_date'], name='ct_t_sd_ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_contract_tenant_code'),
        ),
    ]
