# Generated by Django 4.2.11 on 2026-03-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractpayment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tổng tiền phải thanh toán = amount + vat_amount', max_digits=18),
        ),
        migrations.AddField(
            model_name='contractpayment',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tiền VAT của dòng thanh toán này', max_digits=18),
        ),
        migrations.AddField(
            model_name='contractpayment',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Phần trăm VAT áp dụng cho dòng thanh toán này', max_digits=5),
        ),
        migrations.AlterField(
            model_name='contractpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Số tiền gốc trước VAT', max_digits=18),
        ),
    ]
