# Generated by Django 6.0.2 on 2026-02-19 03:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_alter_company_tenant'),
        ('shops', '0008_remove_shopmember_idx_shopmember_shop_and_more'),
        ('tenants', '0006_alter_tenant_options_alter_tenantdomain_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(choices=[('shop_operation', 'SHOP_OPERATION'), ('build_channel', 'BUILD_CHANNEL'), ('booking', 'BOOKING')], db_index=True, default='shop_operation', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('done', 'Done')], db_index=True, default='active', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='companies.company')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('operation', 'Shop Operation'), ('build_channel', 'Build Channel'), ('booking', 'Booking')], db_index=True, default='operation', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('done', 'Done')], db_index=True, default='active', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('assigned_pm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_project_shops', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_shops', to='projects.project')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='shops.shop')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_shops', to='tenants.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tenant', 'status'], name='idx_project_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tenant', 'type'], name='idx_project_tenant_type'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tenant', 'company'], name='idx_project_tenant_company'),
        ),
        migrations.AddIndex(
            model_name='projectshop',
            index=models.Index(fields=['tenant', 'project'], name='idx_projectshop_tenant_project'),
        ),
        migrations.AddIndex(
            model_name='projectshop',
            index=models.Index(fields=['tenant', 'shop'], name='idx_projectshop_tenant_shop'),
        ),
        migrations.AddConstraint(
            model_name='projectshop',
            constraint=models.UniqueConstraint(fields=('tenant', 'project', 'shop'), name='uq_project_shop_unique'),
        ),
    ]
