# Generated by Django 4.2.11 on 2026-03-10 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(choices=[('shop_operation', 'SHOP_OPERATION'), ('build_channel', 'BUILD_CHANNEL'), ('booking', 'BOOKING')], db_index=True, default='shop_operation', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('done', 'Done'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('health_score', models.PositiveSmallIntegerField(db_index=True, default=100)),
                ('last_activity_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='companies.company')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, default='operation', max_length=30)),
                ('status', models.CharField(db_index=True, default='active', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_pm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_project_shops', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_shops', to='projects.project')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='shops.shop')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_shops', to='tenants.tenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='projectshop',
            constraint=models.UniqueConstraint(fields=('tenant', 'project', 'shop'), name='uq_project_shop_unique'),
        ),
    ]
