# Generated by Django 6.0.2 on 2026-02-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectshop_updated_at_alter_projectshop_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='health_score',
            field=models.PositiveSmallIntegerField(db_index=True, default=100),
        ),
        migrations.AddField(
            model_name='project',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
