# Generated by Django 5.2.11 on 2026-02-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_health_score_project_last_activity_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('done', 'Done'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20),
        ),
    ]
