# Generated by Django 4.2.11 on 2026-02-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='idx_project_tenant_status',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='idx_project_tenant_type',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='idx_project_tenant_company',
        ),
        migrations.RemoveIndex(
            model_name='projectshop',
            name='idx_projectshop_tenant_project',
        ),
        migrations.RemoveIndex(
            model_name='projectshop',
            name='idx_projectshop_tenant_shop',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('done', 'Done'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectshop',
            name='role',
            field=models.CharField(db_index=True, default='operation', max_length=30),
        ),
        migrations.AlterField(
            model_name='projectshop',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=20),
        ),
    ]
