# Generated by Django 4.2.11 on 2026-03-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('founder', 'Founder'), ('leader_channel', 'Leader Channel'), ('leader_booking', 'Leader Booking'), ('leader_operation', 'Leader Operation'), ('account', 'Account'), ('sale', 'Sale'), ('operator', 'Operator'), ('editor', 'Editor')], db_index=True, max_length=50),
        ),
    ]
