# Generated by Django 5.2.11 on 2026-02-21 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('companies', '0004_alter_company_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='membership',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('founder', 'Founder'), ('head', 'Head'), ('account', 'Account'), ('sale', 'Sale'), ('operator', 'Operator')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'is_active'], name='idx_mship_user_active'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['company', 'is_active'], name='idx_mship_company_active'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['role'], name='idx_mship_role'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'company'), name='uq_membership_user_company'),
        ),
    ]
