# Generated by Django 4.2.11 on 2026-03-02 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_tenant_suspended_at_alter_tenant_status_and_more'),
        ('accounts', '0002_alter_membership_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membership',
            name='uq_membership_user_company',
        ),
        migrations.RenameIndex(
            model_name='membership',
            new_name='msh_u_act_idx',
            old_name='idx_mship_user_active',
        ),
        migrations.RenameIndex(
            model_name='membership',
            new_name='msh_c_act_idx',
            old_name='idx_mship_company_active',
        ),
        migrations.RenameIndex(
            model_name='membership',
            new_name='msh_role_idx',
            old_name='idx_mship_role',
        ),
        migrations.AddField(
            model_name='membership',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['tenant'], name='msh_t_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['tenant', 'company', 'is_active'], name='msh_t_co_act_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('tenant', 'user', 'company'), name='uq_mship_t_u_c'),
        ),
    ]
