# Generated by Django 4.2.11 on 2026-03-04 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_tenant_suspended_at_alter_tenant_status_and_more'),
        ('accounts', '0003_remove_membership_uq_membership_user_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant'),
        ),
    ]
