# Generated by Django 4.2.11 on 2026-03-04 04:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_membership_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('max_uses', models.IntegerField(default=10)),
                ('used_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Invite Code',
                'verbose_name_plural': 'Invite Codes',
            },
        ),
    ]
