# Generated by Django 4.2.11 on 2026-03-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_invitecode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitecode',
            options={},
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='max_uses',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
