# Generated by Django 4.2.11 on 2026-03-10 04:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Tên Company')),
                ('max_clients', models.IntegerField(default=5, verbose_name='Số client tối đa')),
                ('months_active', models.IntegerField(default=0, verbose_name='Số tháng hoạt động')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='tenants.agency', verbose_name='Agency quản lý')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['tenant'], name='idx_company_tenant'), models.Index(fields=['is_active'], name='idx_company_active'), models.Index(fields=['tenant', 'is_active'], name='idx_company_tenant_active')],
            },
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uq_company_tenant_name'),
        ),
    ]
