# Generated by Django 6.0.2 on 2026-02-17 08:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('tenants', '0003_alter_agency_options_alter_tenant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-id'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AddField(
            model_name='company',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Cập nhật'),
        ),
        migrations.AlterField(
            model_name='company',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='tenants.agency', verbose_name='Agency quản lý'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='max_clients',
            field=models.IntegerField(default=5, verbose_name='Số client tối đa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='months_active',
            field=models.IntegerField(default=0, verbose_name='Số tháng hoạt động'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên Company'),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['tenant'], name='idx_company_tenant'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active'], name='idx_company_active'),
        ),
    ]
