# Generated by Django 6.0.2 on 2026-02-17 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options_company_is_active_and_more'),
        ('tenants', '0003_alter_agency_options_alter_tenant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='tenants.tenant'),
        ),
    ]
