# Generated by Django 5.2.11 on 2026-02-21 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_tenant'),
        ('tenants', '0009_tenant_suspended_at_alter_tenant_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Tên Company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['tenant', 'is_active'], name='idx_company_tenant_active'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uq_company_tenant_name'),
        ),
    ]
