# Generated by Django 4.2.11 on 2026-03-10 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(db_index=True)),
                ('month', models.DateField(db_index=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('currency', models.CharField(default='VND', max_length=8)),
                ('total_amount', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=16)),
                ('usage_snapshot', models.JSONField(blank=True, default=dict)),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(default='', max_length=128)),
                ('currency', models.CharField(default='VND', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('free_requests', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantUsageMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(db_index=True)),
                ('month', models.DateField(db_index=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('requests', models.BigIntegerField(default=0)),
                ('errors', models.BigIntegerField(default=0)),
                ('slow', models.BigIntegerField(default=0)),
                ('rate_limited', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'month'], name='billing_ten_tenant__092c48_idx')],
                'unique_together': {('tenant_id', 'month')},
            },
        ),
        migrations.CreateModel(
            name='TenantUsageDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('requests', models.BigIntegerField(default=0)),
                ('errors', models.BigIntegerField(default=0)),
                ('slow', models.BigIntegerField(default=0)),
                ('rate_limited', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'date'], name='billing_ten_tenant__1b8104_idx')],
                'unique_together': {('tenant_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_requests', models.PositiveIntegerField(default=0)),
                ('to_requests', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_price', models.PositiveIntegerField(default=0)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='billing.pricingplan')),
            ],
            options={
                'ordering': ['priority', 'from_requests'],
            },
        ),
        migrations.AddIndex(
            model_name='pricingplan',
            index=models.Index(fields=['code', 'is_active'], name='billing_pri_code_339d65_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant_id', 'month'], name='billing_inv_tenant__16fbd0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('tenant_id', 'month')},
        ),
        migrations.AddIndex(
            model_name='pricingtier',
            index=models.Index(fields=['plan', 'priority'], name='billing_pri_plan_id_1e6422_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingtier',
            index=models.Index(fields=['plan', 'from_requests'], name='billing_pri_plan_id_c61cb8_idx'),
        ),
    ]
