# Generated by Django 5.2.11 on 2026-02-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(db_index=True)),
                ('month', models.DateField(db_index=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('currency', models.CharField(default='VND', max_length=8)),
                ('total_amount', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('void', 'Void')], default='draft', max_length=16)),
                ('usage_snapshot', models.JSONField(blank=True, default=dict)),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'month'], name='billing_inv_tenant__16fbd0_idx')],
                'unique_together': {('tenant_id', 'month')},
            },
        ),
        migrations.CreateModel(
            name='TenantUsageDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('requests', models.BigIntegerField(default=0)),
                ('errors', models.BigIntegerField(default=0)),
                ('slow', models.BigIntegerField(default=0)),
                ('rate_limited', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'date'], name='billing_ten_tenant__1b8104_idx')],
                'unique_together': {('tenant_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TenantUsageMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(db_index=True)),
                ('month', models.DateField(db_index=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('requests', models.BigIntegerField(default=0)),
                ('errors', models.BigIntegerField(default=0)),
                ('slow', models.BigIntegerField(default=0)),
                ('rate_limited', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'month'], name='billing_ten_tenant__092c48_idx')],
                'unique_together': {('tenant_id', 'month')},
            },
        ),
    ]
