# Generated by Django 5.2.11 on 2026-02-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=16),
        ),
    ]
