# Generated by Django 5.2.11 on 2026-02-21 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_invoice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(default='', max_length=128)),
                ('currency', models.CharField(default='VND', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('free_requests', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code', 'is_active'], name='billing_pri_code_339d65_idx')],
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_requests', models.PositiveIntegerField(default=0)),
                ('to_requests', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_price', models.PositiveIntegerField(default=0)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='billing.pricingplan')),
            ],
            options={
                'ordering': ['priority', 'from_requests'],
                'indexes': [models.Index(fields=['plan', 'priority'], name='billing_pri_plan_id_1e6422_idx'), models.Index(fields=['plan', 'from_requests'], name='billing_pri_plan_id_c61cb8_idx')],
            },
        ),
    ]
