# Generated by Django 4.2.11 on 2026-03-12 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('title', models.CharField(max_length=500)),
                ('doc_type', models.CharField(choices=[('doc', 'Doc'), ('proposal', 'Proposal'), ('quotation', 'Quotation'), ('contract', 'Contract'), ('appendix', 'Appendix'), ('report', 'Report')], db_index=True, default='doc', max_length=50)),
                ('linked_target_type', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('linked_target_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('content_html', models.TextField(blank=True, default='')),
                ('public_token', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'docs_document',
                'ordering': ('-id',),
                'indexes': [models.Index(fields=['tenant_id', 'doc_type'], name='docs_docume_tenant__97525e_idx'), models.Index(fields=['tenant_id', 'linked_target_type', 'linked_target_id'], name='docs_docume_tenant__26bca1_idx')],
            },
        ),
    ]
