# Generated by Django 4.2.11 on 2026-03-10 04:03

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyMonthlyFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('locked', 'Locked'), ('finalized', 'Finalized')], db_index=True, default='open', max_length=20)),
                ('total_gmv_fee_after_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_fixed_fee_net', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_sale_commission', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_team_bonus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_operating_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('agency_net_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('rule_industry_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Rule Industry Code Snapshot')),
                ('rule_version', models.CharField(blank=True, default='', max_length=50, verbose_name='Rule Version Snapshot')),
                ('rule_engine_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Rule Engine Name Snapshot')),
                ('rule_effective_date', models.DateField(blank=True, null=True, verbose_name='Rule Effective Date Snapshot')),
                ('rule_snapshot_json', models.JSONField(blank=True, null=True, verbose_name='Rule Metadata Snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['month'], name='idx_ag_fin_month'), models.Index(fields=['status'], name='idx_ag_fin_status'), models.Index(fields=['month', 'status'], name='idx_ag_fin_month_status')],
            },
        ),
        migrations.CreateModel(
            name='ShopMonthlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('profit', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('net', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('score', models.IntegerField(default=100)),
                ('risk', models.CharField(default='LOW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_snapshots', to='shops.shop')),
            ],
            options={
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['shop', 'month'], name='idx_shop_snap_shop_month'), models.Index(fields=['month'], name='idx_shop_snap_month')],
                'unique_together': {('shop', 'month')},
            },
        ),
        migrations.CreateModel(
            name='CompanyMonthlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('total_profit', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('total_net', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_snapshots', to='companies.company')),
            ],
            options={
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['company', 'month'], name='idx_co_snap_company_month'), models.Index(fields=['month'], name='idx_co_snap_month')],
                'unique_together': {('company', 'month')},
            },
        ),
    ]
