# Generated by Django 6.0.2 on 2026-02-14 02:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('gmv_percent_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fixed_fee_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_rate_percent', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('tax_rate_fixed', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('net_gmv_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_fixed_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('team_bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sale_commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('company_net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='shops.shop')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('shop', 'month')},
            },
        ),
    ]
