# Generated by Django 6.0.2 on 2026-02-14 03:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyMonthlyFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True, verbose_name='Tháng (ngày 01)')),
                ('status', models.CharField(choices=[('open', 'Open'), ('locked', 'Locked'), ('finalized', 'Finalized')], default='open', max_length=20, verbose_name='Trạng thái')),
                ('total_gmv_fee_after_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Tổng phí % GMV sau thuế')),
                ('total_fixed_fee_net', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Tổng phí cứng (net sau VAT)')),
                ('total_sale_commission', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Tổng hoa hồng Sale')),
                ('total_team_bonus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Tổng thưởng team vận hành')),
                ('total_operating_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Tổng chi phí vận hành (tuỳ chọn)')),
                ('agency_net_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Lợi nhuận net của công ty')),
                ('calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm tính')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm khoá')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm chốt sổ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Tài chính tháng (Snapshot)',
                'verbose_name_plural': 'Tài chính tháng (Snapshot)',
                'ordering': ['-month'],
            },
        ),
        migrations.DeleteModel(
            name='FinancialLedger',
        ),
    ]
