# Generated by Django 6.0.2 on 2026-02-15 13:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('finance', '0002_agencymonthlyfinance_delete_financialledger'),
        ('shops', '0006_alter_shop_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencymonthlyfinance',
            options={'ordering': ['-month']},
        ),
        migrations.AlterField(
            model_name='agencymonthlyfinance',
            name='agency_net_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='agencymonthlyfinance',
            name='calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agencymonthlyfinance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='agencymonthlyfinance',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agencymonthlyfinance',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agencymonthlyfinance',
            name='month',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='agencymonthlyfinance',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('locked', 'Locked'), ('finalized', 'Finalized')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='agencymonthlyfinance',
            name='total_fixed_fee_net',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='agencymonthlyfinance',
            name='total_gmv_fee_after_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='agencymonthlyfinance',
            name='total_operating_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='agencymonthlyfinance',
            name='total_sale_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='agencymonthlyfinance',
            name='total_team_bonus',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='agencymonthlyfinance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='CompanyMonthlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('total_profit', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('total_net', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_snapshots', to='companies.company')),
            ],
            options={
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['company', 'month'], name='finance_com_company_90c069_idx'), models.Index(fields=['month'], name='finance_com_month_0248d6_idx')],
                'unique_together': {('company', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ShopMonthlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('profit', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('net', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('score', models.IntegerField(default=100)),
                ('risk', models.CharField(default='LOW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_snapshots', to='shops.shop')),
            ],
            options={
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['shop', 'month'], name='finance_sho_shop_id_6c6978_idx'), models.Index(fields=['month'], name='finance_sho_month_7398a7_idx')],
                'unique_together': {('shop', 'month')},
            },
        ),
    ]
