# Generated by Django 4.2.11 on 2026-03-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_agencymonthlyfinance_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='companymonthlysnapshot',
            new_name='idx_co_snap_company_month',
            old_name='finance_com_company_90c069_idx',
        ),
        migrations.RenameIndex(
            model_name='companymonthlysnapshot',
            new_name='idx_co_snap_month',
            old_name='finance_com_month_0248d6_idx',
        ),
        migrations.RenameIndex(
            model_name='shopmonthlysnapshot',
            new_name='idx_shop_snap_shop_month',
            old_name='finance_sho_shop_id_6c6978_idx',
        ),
        migrations.RenameIndex(
            model_name='shopmonthlysnapshot',
            new_name='idx_shop_snap_month',
            old_name='finance_sho_month_7398a7_idx',
        ),
        migrations.AddField(
            model_name='agencymonthlyfinance',
            name='rule_effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='Rule Effective Date Snapshot'),
        ),
        migrations.AddField(
            model_name='agencymonthlyfinance',
            name='rule_engine_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Rule Engine Name Snapshot'),
        ),
        migrations.AddField(
            model_name='agencymonthlyfinance',
            name='rule_industry_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Rule Industry Code Snapshot'),
        ),
        migrations.AddField(
            model_name='agencymonthlyfinance',
            name='rule_snapshot_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Rule Metadata Snapshot'),
        ),
        migrations.AddField(
            model_name='agencymonthlyfinance',
            name='rule_version',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Rule Version Snapshot'),
        ),
        migrations.AlterField(
            model_name='agencymonthlyfinance',
            name='month',
            field=models.DateField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agencymonthlyfinance',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('locked', 'Locked'), ('finalized', 'Finalized')], db_index=True, default='open', max_length=20),
        ),
        migrations.AddIndex(
            model_name='agencymonthlyfinance',
            index=models.Index(fields=['month'], name='idx_ag_fin_month'),
        ),
        migrations.AddIndex(
            model_name='agencymonthlyfinance',
            index=models.Index(fields=['status'], name='idx_ag_fin_status'),
        ),
        migrations.AddIndex(
            model_name='agencymonthlyfinance',
            index=models.Index(fields=['month', 'status'], name='idx_ag_fin_month_status'),
        ),
    ]
