# Generated by Django 4.2.11 on 2026-03-05 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0009_tenant_suspended_at_alter_tenant_status_and_more'),
        ('companies', '0004_alter_company_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0010_remove_shopmember_uq_shopmember_shop_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('tieu_de', models.CharField(db_index=True, max_length=200)),
                ('noi_dung', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('info', 'Thông tin'), ('warning', 'Cảnh báo'), ('critical', 'Nghiêm trọng')], db_index=True, default='info', max_length=20)),
                ('entity_kind', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('entity_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'Mới'), ('read', 'Đã đọc'), ('archived', 'Lưu trữ')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.shop')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'status', 'created_at'], name='osn_t_st_ct_idx'), models.Index(fields=['tenant', 'target_user', 'status'], name='osn_t_u_st_idx'), models.Index(fields=['tenant', 'target_role', 'status'], name='osn_t_r_st_idx')],
            },
        ),
    ]
