# Generated by Django 4.2.11 on 2026-03-12 09:46

import apps.os.models_attachment
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('os', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('target_type', models.CharField(choices=[('contract', 'Contract'), ('channel_content', 'Channel Content')], db_index=True, max_length=64)),
                ('target_id', models.BigIntegerField(db_index=True)),
                ('contract_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('channel_content_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('company_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('shop_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('project_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('file', models.FileField(upload_to=apps.os.models_attachment.os_attachment_upload_to)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'os_attachment',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['tenant_id', 'target_type', 'target_id'], name='os_attachme_tenant__aeb8f7_idx'), models.Index(fields=['tenant_id', 'contract_id'], name='os_attachme_tenant__b981c5_idx'), models.Index(fields=['tenant_id', 'channel_content_id'], name='os_attachme_tenant__83fe31_idx'), models.Index(fields=['tenant_id', 'shop_id'], name='os_attachme_tenant__193ba9_idx'), models.Index(fields=['tenant_id', 'project_id'], name='os_attachme_tenant__41c610_idx'), models.Index(fields=['tenant_id', 'is_deleted'], name='os_attachme_tenant__1ae773_idx')],
            },
        ),
    ]
