# Generated by Django 4.2.11 on 2026-03-05 07:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_tenant_suspended_at_alter_tenant_status_and_more'),
        ('os', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(db_index=True, max_length=120)),
                ('dedupe_key', models.CharField(db_index=True, max_length=180, unique=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='new', max_length=20)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
    ]
