# Generated by Django 4.2.11 on 2026-03-10 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên Brand')),
                ('code', models.SlugField(blank=True, max_length=100, null=True, verbose_name='Mã Brand (tuỳ chọn)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='companies.company', verbose_name='Company')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BrandMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('viewer', 'Viewer')], default='viewer', max_length=20, verbose_name='Role')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='brands.brand', verbose_name='Brand')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_members', to='tenants.tenant', verbose_name='Tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Brand member',
                'verbose_name_plural': 'Brand members',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['tenant'], name='idx_brandmember_tenant'), models.Index(fields=['user'], name='idx_brandmember_user'), models.Index(fields=['is_active'], name='idx_brandmember_active')],
            },
        ),
        migrations.AddConstraint(
            model_name='brandmember',
            constraint=models.UniqueConstraint(fields=('brand', 'user'), name='uq_brandmember_brand_user'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['tenant'], name='idx_brand_tenant'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['tenant', 'is_active'], name='idx_brand_tenant_active'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['company'], name='idx_brand_company'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(fields=('tenant', 'company', 'name'), name='uq_brand_tenant_company_name'),
        ),
    ]
