# Generated by Django 6.0.2 on 2026-02-14 06:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-id'], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.RemoveField(
            model_name='brand',
            name='description',
        ),
        migrations.AddField(
            model_name='brand',
            name='code',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Mã Brand (tuỳ chọn)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='companies.company', verbose_name='Agency/Company'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên Brand'),
        ),
        migrations.CreateModel(
            name='BrandMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('viewer', 'Viewer')], default='viewer', max_length=20, verbose_name='Role')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='brands.brand', verbose_name='Brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Brand member',
                'verbose_name_plural': 'Brand members',
                'ordering': ['-id'],
                'unique_together': {('brand', 'user')},
            },
        ),
    ]
