# Generated by Django 6.0.2 on 2026-02-18 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_alter_brand_options_remove_brand_description_and_more'),
        ('companies', '0003_alter_company_tenant'),
        ('tenants', '0006_alter_tenant_options_alter_tenantdomain_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandmember',
            options={'ordering': ['-id']},
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='brand',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='brandmember',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='brands.brand'),
        ),
        migrations.AlterField(
            model_name='brandmember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='brandmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
        migrations.AlterField(
            model_name='brandmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('tenant', 'company', 'name')},
        ),
    ]
