# Generated by Django 6.0.2 on 2026-02-18 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_alter_brandmember_options_and_more'),
        ('companies', '0003_alter_company_tenant'),
        ('tenants', '0006_alter_tenant_options_alter_tenantdomain_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandmember',
            options={'ordering': ['-id'], 'verbose_name': 'Brand member', 'verbose_name_plural': 'Brand members'},
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='brandmember',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='brandmember',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brand_members', to='tenants.tenant', verbose_name='Tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='companies.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Cập nhật'),
        ),
        migrations.AlterField(
            model_name='brandmember',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='brands.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='brandmember',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='brandmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('viewer', 'Viewer')], default='viewer', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='brandmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['tenant'], name='idx_brand_tenant'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['tenant', 'is_active'], name='idx_brand_tenant_active'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['company'], name='idx_brand_company'),
        ),
        migrations.AddIndex(
            model_name='brandmember',
            index=models.Index(fields=['tenant'], name='idx_brandmember_tenant'),
        ),
        migrations.AddIndex(
            model_name='brandmember',
            index=models.Index(fields=['user'], name='idx_brandmember_user'),
        ),
        migrations.AddIndex(
            model_name='brandmember',
            index=models.Index(fields=['is_active'], name='idx_brandmember_active'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(fields=('tenant', 'company', 'name'), name='uq_brand_tenant_company_name'),
        ),
        migrations.AddConstraint(
            model_name='brandmember',
            constraint=models.UniqueConstraint(fields=('brand', 'user'), name='uq_brandmember_brand_user'),
        ),
    ]
