# Generated by Django 4.2.11 on 2026-03-10 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xoá'), ('bulk_update', 'Cập nhật hàng loạt'), ('export_csv', 'Xuất CSV')], db_index=True, max_length=20, verbose_name='Hành động')),
                ('app_label', models.CharField(db_index=True, max_length=100, verbose_name='App')),
                ('model_name', models.CharField(db_index=True, max_length=100, verbose_name='Model')),
                ('object_pk', models.CharField(db_index=True, max_length=64, verbose_name='ID đối tượng')),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('trace_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('method', models.CharField(blank=True, default='', max_length=16)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referer', models.TextField(blank=True, null=True)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['app_label', 'model_name'], name='idx_audit_model'), models.Index(fields=['object_pk'], name='idx_audit_objectpk'), models.Index(fields=['tenant', 'created_at'], name='idx_audit_tenant_time'), models.Index(fields=['request_id', 'created_at'], name='idx_audit_req_time')],
            },
        ),
    ]
