# Generated by Django 6.0.2 on 2026-02-17 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog_method_auditlog_path_auditlog_referer_and_more'),
        ('tenants', '0003_alter_agency_options_alter_tenant_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='idx_audit_model',
            old_name='core_auditl_app_lab_2f0dea_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='idx_audit_objectpk',
            old_name='core_auditl_object__807438_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='idx_audit_created',
            old_name='core_auditl_created_dc23ea_idx',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', 'created_at'], name='idx_audit_tenant_time'),
        ),
    ]
