# Generated by Django 6.0.2 on 2026-02-20 08:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemactivitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='systemactivitylog',
            name='idx_syslog_tenant_time',
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nhật ký thay đổi', 'verbose_name_plural': 'Nhật ký thay đổi'},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='idx_audit_created',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='changed_fields',
            field=models.JSONField(blank=True, default=list, verbose_name='Field thay đổi'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='Meta bổ sung'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xoá'), ('bulk_update', 'Cập nhật hàng loạt'), ('export_csv', 'Xuất CSV')], db_index=True, max_length=20, verbose_name='Hành động'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='after',
            field=models.JSONField(blank=True, null=True, verbose_name='Sau'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='app_label',
            field=models.CharField(db_index=True, max_length=100, verbose_name='App'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='before',
            field=models.JSONField(blank=True, null=True, verbose_name='Trước'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Thời gian'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='method',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Method'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_pk',
            field=models.CharField(db_index=True, max_length=64, verbose_name='ID đối tượng'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='path',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Đường dẫn'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='referer',
            field=models.TextField(blank=True, null=True, verbose_name='Referer'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User-Agent'),
        ),
        migrations.DeleteModel(
            name='SystemActivityLog',
        ),
    ]
