# Generated by Django 6.0.2 on 2026-02-20 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_systemactivitylog_idx_syslog_tenant_time_and_more'),
        ('tenants', '0006_alter_tenant_options_alter_tenantdomain_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Request ID'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='trace_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='Trace ID'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['request_id', 'created_at'], name='idx_audit_req_time'),
        ),
    ]
