# Generated by Django 4.2.11 on 2026-03-10 04:03

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, default='', max_length=255, verbose_name='Tên file')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Dung lượng (bytes)')),
                ('dry_run', models.BooleanField(default=True, verbose_name='Chạy thử (dry-run)')),
                ('status', models.CharField(choices=[('pending', 'Chờ'), ('running', 'Đang chạy'), ('success', 'Thành công'), ('failed', 'Thất bại')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái')),
                ('total_rows', models.IntegerField(default=0, verbose_name='Tổng dòng')),
                ('valid_rows', models.IntegerField(default=0, verbose_name='Dòng hợp lệ')),
                ('error_rows', models.IntegerField(default=0, verbose_name='Dòng lỗi')),
                ('created', models.IntegerField(default=0, verbose_name='Tạo mới')),
                ('updated', models.IntegerField(default=0, verbose_name='Cập nhật')),
                ('months_touched', models.JSONField(blank=True, null=True, verbose_name='Các tháng bị ảnh hưởng')),
                ('preview', models.JSONField(blank=True, null=True, verbose_name='Preview (tối đa 30)')),
                ('errors_preview', models.JSONField(blank=True, null=True, verbose_name='Lỗi preview (tối đa 200)')),
                ('message', models.TextField(blank=True, default='', verbose_name='Ghi chú / thông báo')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Bắt đầu lúc')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Kết thúc lúc')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tạo lúc')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Lịch sử import',
                'verbose_name_plural': 'Lịch sử import',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Tháng (YYYY-MM-01)')),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='GMV / Doanh thu')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Chi phí')),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Phí cứng (gross)')),
                ('vat_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='VAT % (0/8/10)')),
                ('sale_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Sale % (3-6)')),
                ('service_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='% GMV fee')),
                ('percent_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='GMV fee gross')),
                ('gmv_fee_after_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='GMV fee after tax (70%)')),
                ('fixed_fee_net', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Phí cứng net (trừ VAT)')),
                ('fixed_fee_net_after_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Phí cứng net after tax')),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Profit (base)')),
                ('growth_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Growth %')),
                ('bonus_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Bonus %')),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Team bonus amount')),
                ('sale_commission', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Sale commission')),
                ('company_net_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Company net profit')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tạo lúc')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='shops.shop', verbose_name='Shop')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_performances', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Hiệu suất theo tháng',
                'verbose_name_plural': 'Hiệu suất theo tháng',
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['tenant'], name='idx_perf_tenant'), models.Index(fields=['month'], name='idx_perf_month'), models.Index(fields=['tenant', 'month'], name='idx_perf_tenant_month'), models.Index(fields=['shop', 'month'], name='idx_perf_shop_month')],
            },
        ),
        migrations.AddConstraint(
            model_name='monthlyperformance',
            constraint=models.UniqueConstraint(fields=('tenant', 'shop', 'month'), name='uq_perf_tenant_shop_month'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['tenant', 'created_at'], name='idx_importjob_tenant_time'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['status'], name='idx_importjob_status'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['created_at'], name='idx_importjob_created_at'),
        ),
    ]
