# Generated by Django 6.0.2 on 2026-02-12 23:54

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('service_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('percent_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('growth_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('bonus_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Monthly Performance',
                'verbose_name_plural': 'Monthly Performances',
                'ordering': ['-month'],
                'unique_together': {('shop', 'month')},
            },
        ),
    ]
