# Generated by Django 6.0.2 on 2026-02-13 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('gmv', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gmv_fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gmv_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gmv_net_after_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('team_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('team_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0.1, max_digits=4)),
                ('sale_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sale_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('agency_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='shops.shop')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('shop', 'month')},
            },
        ),
    ]
