# Generated by Django 6.0.2 on 2026-02-13 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_commissionledger'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyperformance',
            options={'ordering': ['-month']},
        ),
        migrations.AddField(
            model_name='monthlyperformance',
            name='company_net_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='monthlyperformance',
            name='fixed_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='monthlyperformance',
            name='fixed_fee_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='monthlyperformance',
            name='gmv_fee_after_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='monthlyperformance',
            name='sale_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='monthlyperformance',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='shops.shop'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CommissionLedger',
        ),
    ]
