# Generated by Django 6.0.2 on 2026-02-14 03:25

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_alter_monthlyperformance_options_and_more'),
        ('shops', '0002_alter_shop_options_shop_client_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyMonthlyFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('total_gmv_fee_after_tax', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_fixed_fee_net', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_sale_commission', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_team_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_operating_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('agency_net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.AlterModelOptions(
            name='monthlyperformance',
            options={'ordering': ['-month'], 'verbose_name': 'Hiệu suất tháng', 'verbose_name_plural': 'Hiệu suất tháng'},
        ),
        migrations.AddField(
            model_name='monthlyperformance',
            name='fixed_fee_net_after_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Fixed fee net after tax (Phí cứng sau VAT & TNDN)'),
        ),
        migrations.AddField(
            model_name='monthlyperformance',
            name='sale_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=5, verbose_name='Sale % (Hoa hồng sale)'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Bonus amount (Tiền thưởng team)'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='bonus_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Bonus % (Tỷ lệ thưởng team)'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='company_net_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Company net profit (Lợi nhuận ròng công ty)'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cost (Chi phí)'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='fixed_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Fixed fee (Phí cứng)'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='fixed_fee_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Fixed fee net (Phí cứng sau VAT)'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='gmv_fee_after_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='GMV fee after tax 70% (Doanh thu áp dụng thưởng)'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='growth_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Growth % (Tăng trưởng)'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='month',
            field=models.DateField(verbose_name='Tháng'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='percent_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='GMV fee (Tiền phí % GMV)'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Profit (Doanh thu áp dụng thưởng)'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='GMV (Tổng doanh thu)'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='sale_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Sale commission (Hoa hồng sale)'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='service_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Service % (Phí theo GMV)'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='shops.shop', verbose_name='Shop (gian hàng)'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='VAT % (Phí cứng)'),
        ),
    ]
