# Generated by Django 6.0.2 on 2026-02-14 14:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_agencymonthlyfinance_and_more'),
        ('shops', '0006_alter_shop_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgencyMonthlyFinance',
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Tiền thưởng team'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='bonus_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='% thưởng team'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='company_net_profit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Net profit công ty'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Chi phí'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='fixed_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Phí cứng (gross)'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='fixed_fee_net',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Phí cứng net (sau VAT)'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='fixed_fee_net_after_tax',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Phí cứng net sau thuế'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='gmv_fee_after_tax',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Phí % GMV sau thuế'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='growth_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, verbose_name='% tăng trưởng'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='percent_fee_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Phí % GMV (gross)'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='profit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Profit base (GMV fee after tax)'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='revenue',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='GMV / Doanh thu'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='sale_commission',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Hoa hồng sale'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='sale_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='% Sale (phí cứng net after tax)'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='service_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='% phí GMV'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='shops.shop', verbose_name='Shop'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='VAT % (phí cứng)'),
        ),
    ]
