# Generated by Django 6.0.2 on 2026-02-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_delete_agencymonthlyfinance_and_more'),
        ('shops', '0006_alter_shop_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyperformance',
            options={'ordering': ['-month']},
        ),
        migrations.AddIndex(
            model_name='monthlyperformance',
            index=models.Index(fields=['shop', 'month'], name='performance_shop_id_90abac_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyperformance',
            index=models.Index(fields=['month'], name='performance_month_5660c7_idx'),
        ),
    ]
