# Generated by Django 6.0.2 on 2026-02-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_alter_monthlyperformance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyperformance',
            options={'ordering': ['-month'], 'verbose_name': 'Hiệu suất tháng', 'verbose_name_plural': 'Hiệu suất tháng'},
        ),
    ]
