# Generated by Django 6.0.2 on 2026-02-14 17:35

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0007_alter_monthlyperformance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyperformance',
            options={'ordering': ['-month'], 'verbose_name': 'Monthly Performance', 'verbose_name_plural': 'Monthly Performances'},
        ),
        migrations.RemoveIndex(
            model_name='monthlyperformance',
            name='performance_shop_id_90abac_idx',
        ),
        migrations.RemoveIndex(
            model_name='monthlyperformance',
            name='performance_month_5660c7_idx',
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Team bonus amount'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='bonus_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Bonus %'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='company_net_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Company net profit'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Chi phí'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='fixed_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Phí cứng (gross)'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='fixed_fee_net',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Phí cứng net (trừ VAT)'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='fixed_fee_net_after_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Phí cứng net after tax'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='gmv_fee_after_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='GMV fee after tax (70%)'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='growth_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Growth %'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='month',
            field=models.DateField(verbose_name='Tháng (YYYY-MM-01)'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='percent_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='GMV fee gross'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Profit (base)'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='GMV / Doanh thu'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='sale_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Sale commission'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='sale_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Sale % (3-6)'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='service_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='% GMV fee'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='VAT % (0/8/10)'),
        ),
    ]
