# Generated by Django 6.0.2 on 2026-02-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0008_alter_monthlyperformance_options_and_more'),
        ('shops', '0006_alter_shop_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyperformance',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='monthlyperformance',
            index=models.Index(fields=['month'], name='idx_perf_month'),
        ),
        migrations.AddIndex(
            model_name='monthlyperformance',
            index=models.Index(fields=['shop', 'month'], name='idx_perf_shop_month'),
        ),
        migrations.AddConstraint(
            model_name='monthlyperformance',
            constraint=models.UniqueConstraint(fields=('shop', 'month'), name='uq_perf_shop_month'),
        ),
    ]
