# Generated by Django 6.0.2 on 2026-02-16 10:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0010_importjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importjob',
            options={'ordering': ['-id'], 'verbose_name': 'Lịch sử import', 'verbose_name_plural': 'Lịch sử import'},
        ),
        migrations.AlterModelOptions(
            name='monthlyperformance',
            options={'ordering': ['-month'], 'verbose_name': 'Hiệu suất theo tháng', 'verbose_name_plural': 'Hiệu suất theo tháng'},
        ),
        migrations.AlterField(
            model_name='importjob',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tạo lúc'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perf_import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='created_count',
            field=models.IntegerField(default=0, verbose_name='Tạo mới'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='dry_run',
            field=models.BooleanField(default=True, verbose_name='Chạy thử (dry-run)'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='errors',
            field=models.JSONField(blank=True, null=True, verbose_name='Danh sách lỗi'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tên file'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kết thúc lúc'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='Ghi chú / thông báo'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='months_touched',
            field=models.JSONField(blank=True, null=True, verbose_name='Các tháng bị ảnh hưởng'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bắt đầu lúc'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ'), ('running', 'Đang chạy'), ('done', 'Hoàn tất'), ('failed', 'Thất bại')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='total_rows',
            field=models.IntegerField(default=0, verbose_name='Tổng dòng'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='updated_count',
            field=models.IntegerField(default=0, verbose_name='Cập nhật'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='valid_rows',
            field=models.IntegerField(default=0, verbose_name='Dòng hợp lệ'),
        ),
        migrations.AlterField(
            model_name='monthlyperformance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tạo lúc'),
        ),
    ]
