# Generated by Django 6.0.2 on 2026-02-18 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0012_importjob_actor_importjob_file_size_importjob_tenant'),
        ('shops', '0008_remove_shopmember_idx_shopmember_shop_and_more'),
        ('tenants', '0006_alter_tenant_options_alter_tenantdomain_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='monthlyperformance',
            name='uq_perf_shop_month',
        ),
        migrations.RenameField(
            model_name='importjob',
            old_name='created_count',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='importjob',
            old_name='updated_count',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='importjob',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='importjob',
            name='errors',
        ),
        migrations.AddField(
            model_name='importjob',
            name='error_rows',
            field=models.IntegerField(default=0, verbose_name='Dòng lỗi'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='errors_preview',
            field=models.JSONField(blank=True, null=True, verbose_name='Lỗi preview (tối đa 200)'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='preview',
            field=models.JSONField(blank=True, null=True, verbose_name='Preview (tối đa 30)'),
        ),
        migrations.AddField(
            model_name='monthlyperformance',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_performances', to='tenants.tenant', verbose_name='Tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='importjob',
            name='file_size',
            field=models.BigIntegerField(default=0, verbose_name='Dung lượng (bytes)'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ'), ('running', 'Đang chạy'), ('success', 'Thành công'), ('failed', 'Thất bại')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['tenant', 'created_at'], name='idx_importjob_tenant_time'),
        ),
        migrations.AddIndex(
            model_name='monthlyperformance',
            index=models.Index(fields=['tenant'], name='idx_perf_tenant'),
        ),
        migrations.AddIndex(
            model_name='monthlyperformance',
            index=models.Index(fields=['tenant', 'month'], name='idx_perf_tenant_month'),
        ),
        migrations.AddConstraint(
            model_name='monthlyperformance',
            constraint=models.UniqueConstraint(fields=('tenant', 'shop', 'month'), name='uq_perf_tenant_shop_month'),
        ),
    ]
