# Generated by Django 6.0.2 on 2026-02-17 07:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_tenantsubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['-id'], 'verbose_name': 'Agency', 'verbose_name_plural': 'Danh sách Agency'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['-id'], 'verbose_name': 'Tenant', 'verbose_name_plural': 'Tenants'},
        ),
        migrations.AddField(
            model_name='tenant',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='tenants.agency', verbose_name='Agency quản lý'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
