# Generated by Django 6.0.2 on 2026-02-17 13:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_agency_options_alter_tenant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['-id'], 'verbose_name': 'Tenant', 'verbose_name_plural': 'Danh sách Tenant'},
        ),
        migrations.AddField(
            model_name='agency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='tenants.agency', verbose_name='Agency quản lý'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Hoạt động'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tên Tenant'),
        ),
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Ví dụ: heighttech.localhost hoặc heighttech.yourdomain.com', max_length=255, unique=True, verbose_name='Domain/Subdomain')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary domain')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Tenant domain',
                'verbose_name_plural': 'Tenant domains',
                'ordering': ['-is_primary', 'domain'],
                'indexes': [models.Index(fields=['domain'], name='idx_tenantdomain_domain'), models.Index(fields=['tenant', 'is_active'], name='idx_tenantdomain_tenant')],
            },
        ),
    ]
