# Generated by Django 6.0.2 on 2026-02-17 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_tenant_options_agency_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['-id'], 'verbose_name': 'Tenant', 'verbose_name_plural': 'Tenants'},
        ),
        migrations.AlterModelOptions(
            name='tenantdomain',
            options={'ordering': ['-id'], 'verbose_name': 'Tenant domain', 'verbose_name_plural': 'Tenant domains'},
        ),
        migrations.RemoveIndex(
            model_name='tenantdomain',
            name='idx_tenantdomain_tenant',
        ),
        migrations.RenameIndex(
            model_name='tenantdomain',
            new_name='idx_tdomain_domain',
            old_name='idx_tenantdomain_domain',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='tenants.agency', verbose_name='Agency'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tenantdomain',
            name='domain',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tenantdomain',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tenantdomain',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenantdomain',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='tenantdomain',
            index=models.Index(fields=['tenant', 'is_primary'], name='idx_tdomain_primary'),
        ),
        migrations.RemoveField(
            model_name='tenantdomain',
            name='updated_at',
        ),
    ]
