# Generated by Django 6.0.2 on 2026-02-17 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_tenant_options_alter_tenantdomain_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['-id'], 'verbose_name': 'Tenant', 'verbose_name_plural': 'Danh sách Tenant'},
        ),
        migrations.AlterModelOptions(
            name='tenantdomain',
            options={'ordering': ['domain'], 'verbose_name': 'Tenant Domain', 'verbose_name_plural': 'Tenant Domains'},
        ),
        migrations.RemoveIndex(
            model_name='tenantdomain',
            name='idx_tdomain_domain',
        ),
        migrations.RemoveIndex(
            model_name='tenantdomain',
            name='idx_tdomain_primary',
        ),
        migrations.AddField(
            model_name='tenantdomain',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='tenants.agency', verbose_name='Agency quản lý'),
        ),
        migrations.AlterField(
            model_name='tenantdomain',
            name='domain',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='tenantdomain',
            index=models.Index(fields=['tenant', 'is_active'], name='idx_td_tenant_active'),
        ),
    ]
