# Generated by Django 5.2.11 on 2026-02-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_alter_tenant_options_alter_tenantdomain_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='feature_flags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='req_per_min_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
