# Generated by Django 5.2.11 on 2026-02-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_tenant_feature_flags_tenant_plan_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenantdomain',
            new_name='tenants_ten_tenant__975e0f_idx',
            old_name='idx_td_tenant_active',
        ),
        migrations.AddField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=16),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['status'], name='tenants_ten_status_e7eaee_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['plan'], name='tenants_ten_plan_2744ca_idx'),
        ),
    ]
