# Generated by Django 5.2.11 on 2026-02-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_rename_idx_td_tenant_active_tenants_ten_tenant__975e0f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=16),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['is_active'], name='tenants_ten_is_acti_8f654a_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantdomain',
            index=models.Index(fields=['domain', 'is_active'], name='tenants_ten_domain_1eabe2_idx'),
        ),
    ]
