# Generated by Django 4.2.11 on 2026-03-10 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên shop')),
                ('platform', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sàn (Shopee/TikTok/Lazada...)')),
                ('code', models.SlugField(blank=True, max_length=100, null=True, verbose_name='Mã shop (tuỳ chọn)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], db_index=True, default='active', max_length=20, verbose_name='Trạng thái')),
                ('industry_code', models.CharField(db_index=True, default='default', help_text='Ví dụ: default, ecommerce, agency, ...', max_length=64, verbose_name='Industry code')),
                ('rule_version', models.CharField(db_index=True, default='v1', help_text='Ví dụ: v1, v2, ... (code-based rules)', max_length=32, verbose_name='Rule version')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='brands.brand', verbose_name='Brand')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('operator', 'Operator'), ('viewer', 'Viewer')], default='viewer', max_length=20, verbose_name='Role')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='shops.shop', verbose_name='Shop')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_members', to='tenants.tenant', verbose_name='Tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Shop member',
                'verbose_name_plural': 'Shop members',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['tenant'], name='idx_shopmember_tenant'), models.Index(fields=['tenant', 'user'], name='idx_shopmember_tenant_user'), models.Index(fields=['tenant', 'shop'], name='idx_shopmember_tenant_shop'), models.Index(fields=['is_active'], name='idx_shopmember_active')],
            },
        ),
        migrations.AddConstraint(
            model_name='shopmember',
            constraint=models.UniqueConstraint(fields=('tenant', 'shop', 'user'), name='uq_shopmember_tenant_shop_user'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['tenant'], name='idx_shop_tenant'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['tenant', 'is_active'], name='idx_shop_tenant_active'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['brand'], name='idx_shop_brand'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['status'], name='idx_shop_status'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['tenant', 'industry_code', 'rule_version'], name='idx_shop_rule'),
        ),
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.UniqueConstraint(fields=('tenant', 'brand', 'name'), name='uq_shop_tenant_brand_name'),
        ),
    ]
