# Generated by Django 6.0.2 on 2026-02-12 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('shopee', 'Shopee'), ('lazada', 'Lazada'), ('tiktok', 'TikTok'), ('website', 'Website')], default='shopee', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='brands.brand')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('brand', 'name')},
            },
        ),
    ]
