# Generated by Django 6.0.2 on 2026-02-14 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('shops', '0002_alter_shop_options_shop_client_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-created_at'], 'verbose_name': 'Shop', 'verbose_name_plural': 'Shops'},
        ),
        migrations.RemoveField(
            model_name='shop',
            name='client_owner',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='platform',
        ),
        migrations.AddField(
            model_name='shop',
            name='ended_at',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc hợp tác'),
        ),
        migrations.AddField(
            model_name='shop',
            name='started_at',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu hợp tác'),
        ),
        migrations.AddField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('terminated', 'Terminated')], default='active', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddField(
            model_name='shop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='brands.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên shop'),
        ),
    ]
