# Generated by Django 6.0.2 on 2026-02-14 06:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_shop_options_remove_shop_client_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Shop', 'verbose_name_plural': 'Shops'},
        ),
        migrations.AddField(
            model_name='shop',
            name='code',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Mã shop (tuỳ chọn)'),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AddField(
            model_name='shop',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sàn (Shopee/Lazada/Tiktok...)'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='ended_at',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='started_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='active', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc'),
        ),
        migrations.CreateModel(
            name='ShopMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('operator', 'Operator'), ('viewer', 'Viewer')], default='viewer', max_length=20, verbose_name='Role')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='shops.shop', verbose_name='Shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Shop member',
                'verbose_name_plural': 'Shop members',
                'ordering': ['-id'],
                'unique_together': {('shop', 'user')},
            },
        ),
    ]
