# Generated by Django 6.0.2 on 2026-02-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_alter_shop_options_shop_code_shop_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-updated_at', '-id'], 'verbose_name': 'Shop', 'verbose_name_plural': 'Shops'},
        ),
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='started_at',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Cập nhật'),
        ),
    ]
