# Generated by Django 6.0.2 on 2026-02-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_alter_shop_options_shop_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Shop', 'verbose_name_plural': 'Shops'},
        ),
    ]
