# Generated by Django 6.0.2 on 2026-02-18 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_alter_brandmember_options_and_more'),
        ('shops', '0006_alter_shop_options'),
        ('tenants', '0006_alter_tenant_options_alter_tenantdomain_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shop',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='shopmember',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shop',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='tenants.tenant', verbose_name='Tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sàn (Shopee/TikTokShop/...)'),
        ),
        migrations.AlterField(
            model_name='shopmember',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Active'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['tenant'], name='idx_shop_tenant'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['tenant', 'is_active'], name='idx_shop_tenant_active'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['brand'], name='idx_shop_brand'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['status'], name='idx_shop_status'),
        ),
        migrations.AddIndex(
            model_name='shopmember',
            index=models.Index(fields=['shop'], name='idx_shopmember_shop'),
        ),
        migrations.AddIndex(
            model_name='shopmember',
            index=models.Index(fields=['user'], name='idx_shopmember_user'),
        ),
        migrations.AddIndex(
            model_name='shopmember',
            index=models.Index(fields=['is_active'], name='idx_shopmember_active'),
        ),
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.UniqueConstraint(fields=('tenant', 'brand', 'name'), name='uq_shop_tenant_brand_name'),
        ),
        migrations.AddConstraint(
            model_name='shopmember',
            constraint=models.UniqueConstraint(fields=('shop', 'user'), name='uq_shopmember_shop_user'),
        ),
    ]
