# Generated by Django 6.0.2 on 2026-02-18 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_alter_shop_unique_together_and_more'),
        ('tenants', '0006_alter_tenant_options_alter_tenantdomain_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shopmember',
            name='idx_shopmember_shop',
        ),
        migrations.AddField(
            model_name='shopmember',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shop_members', to='tenants.tenant', verbose_name='Tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sàn (Shopee/TikTok/Lazada...)'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], db_index=True, default='active', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddIndex(
            model_name='shopmember',
            index=models.Index(fields=['tenant'], name='idx_shopmember_tenant'),
        ),
    ]
