# Generated by Django 4.2.11 on 2026-02-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_remove_shopmember_idx_shopmember_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='industry_code',
            field=models.CharField(db_index=True, default='default', help_text='Ví dụ: default, ecommerce, agency, ...', max_length=64, verbose_name='Industry code'),
        ),
        migrations.AddField(
            model_name='shop',
            name='rule_version',
            field=models.CharField(db_index=True, default='v1', help_text='Ví dụ: v1, v2, ... (code-based rules)', max_length=32, verbose_name='Rule version'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['tenant', 'industry_code', 'rule_version'], name='idx_shop_rule'),
        ),
    ]
