# Generated by Django 4.2.11 on 2026-03-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_shop_industry_code_shop_rule_version_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shopmember',
            name='uq_shopmember_shop_user',
        ),
        migrations.RemoveIndex(
            model_name='shopmember',
            name='idx_shopmember_user',
        ),
        migrations.AddIndex(
            model_name='shopmember',
            index=models.Index(fields=['tenant', 'user'], name='idx_shopmember_tenant_user'),
        ),
        migrations.AddIndex(
            model_name='shopmember',
            index=models.Index(fields=['tenant', 'shop'], name='idx_shopmember_tenant_shop'),
        ),
        migrations.AddConstraint(
            model_name='shopmember',
            constraint=models.UniqueConstraint(fields=('tenant', 'shop', 'user'), name='uq_shopmember_tenant_shop_user'),
        ),
    ]
