# Generated by Django 4.2.11 on 2026-03-10 04:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('shops', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('revenue', 'Doanh thu'), ('expense', 'Chi phí')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('source_type', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('source_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contract')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.shop')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['tenant', 'entry_type'], name='ledger_t_tp_idx'), models.Index(fields=['tenant', 'contract'], name='ledger_t_ct_idx')],
            },
        ),
    ]
