# Generated by Django 6.0.2 on 2026-02-14 16:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0002_alter_brand_options_remove_brand_description_and_more'),
        ('companies', '0001_initial'),
        ('shops', '0006_alter_shop_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Tháng (YYYY-MM-01)')),
                ('revenue_3m', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('profit_3m', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('net_3m', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('margin_3m', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('growth_last_mom', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('score', models.IntegerField(default=0)),
                ('risk', models.CharField(default='LOW', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_health_snapshots', to='brands.brand', verbose_name='Brand')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_health_snapshots', to='companies.company', verbose_name='Company')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to='shops.shop', verbose_name='Shop')),
            ],
            options={
                'verbose_name': 'Shop Health Snapshot',
                'verbose_name_plural': 'Shop Health Snapshots',
                'ordering': ('-month', '-score'),
                'indexes': [models.Index(fields=['month', 'risk'], name='intelligenc_month_1d57ca_idx'), models.Index(fields=['month', 'company'], name='intelligenc_month_6819dd_idx'), models.Index(fields=['month', 'shop'], name='intelligenc_month_2bbdc9_idx')],
                'unique_together': {('month', 'shop')},
            },
        ),
    ]
