# Generated by Django 4.2.11 on 2026-03-10 04:03

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FounderInsightSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kpi', models.JSONField(blank=True, default=dict)),
                ('forecast', models.JSONField(blank=True, default=dict)),
                ('alerts', models.JSONField(blank=True, default=list)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('insights', models.JSONField(blank=True, default=dict)),
                ('shop_health', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='founder_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Tháng (YYYY-MM-01)')),
                ('revenue_3m', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('profit_3m', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('net_3m', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('margin_3m', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('growth_last_mom', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('score', models.IntegerField(default=0)),
                ('risk', models.CharField(default='LOW', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_health_snapshots', to='brands.brand', verbose_name='Brand')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_health_snapshots', to='companies.company', verbose_name='Company')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to='shops.shop', verbose_name='Shop')),
            ],
            options={
                'verbose_name': 'Shop Health Snapshot',
                'verbose_name_plural': 'Shop Health Snapshots',
                'ordering': ('-month', '-score'),
                'indexes': [models.Index(fields=['month', 'risk'], name='idx_shsnap_month_risk'), models.Index(fields=['month', 'company'], name='idx_shsnap_month_company'), models.Index(fields=['month', 'shop'], name='idx_shsnap_month_shop')],
                'unique_together': {('month', 'shop')},
            },
        ),
        migrations.CreateModel(
            name='ShopActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(blank=True, null=True)),
                ('shop_id', models.IntegerField(db_index=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('shop_name', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2')], default='P1', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Mở'), ('doing', 'Đang làm'), ('blocked', 'Bị chặn'), ('done', 'Hoàn thành'), ('verified', 'Đã xác nhận')], default='open', max_length=20)),
                ('source', models.CharField(choices=[('founder_insight', 'Founder Insight'), ('manual', 'Manual'), ('api', 'API')], db_index=True, default='founder_insight', max_length=50)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_shop_action_items', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['month', 'shop_id'], name='idx_action_month_shop'), models.Index(fields=['status'], name='idx_action_status'), models.Index(fields=['severity'], name='idx_action_sev'), models.Index(fields=['source'], name='idx_action_source'), models.Index(fields=['due_at'], name='idx_action_due')],
            },
        ),
        migrations.AddConstraint(
            model_name='shopactionitem',
            constraint=models.UniqueConstraint(fields=('month', 'shop_id', 'title', 'source'), name='uq_action_month_shop_title_source'),
        ),
        migrations.AddIndex(
            model_name='founderinsightsnapshot',
            index=models.Index(fields=['month'], name='idx_insnap_month'),
        ),
        migrations.AddIndex(
            model_name='founderinsightsnapshot',
            index=models.Index(fields=['generated_at'], name='idx_insnap_gen'),
        ),
    ]
