# Generated by Django 6.0.2 on 2026-02-16 12:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FounderInsightSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kpi', models.JSONField(blank=True, default=dict)),
                ('forecast', models.JSONField(blank=True, default=dict)),
                ('alerts', models.JSONField(blank=True, default=list)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('insights', models.JSONField(blank=True, default=dict)),
                ('shop_health', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='founder_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['month'], name='idx_insnap_month'), models.Index(fields=['generated_at'], name='idx_insnap_gen')],
            },
        ),
    ]
