# Generated by Django 6.0.2 on 2026-02-16 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_founderinsightsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(blank=True, null=True)),
                ('shop_id', models.IntegerField(db_index=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('shop_name', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(blank=True, default='P1', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('doing', 'Doing'), ('done', 'Done')], default='open', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['month', 'shop_id'], name='idx_action_month_shop'), models.Index(fields=['status'], name='idx_action_status')],
            },
        ),
    ]
