# Generated by Django 6.0.2 on 2026-02-16 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0003_shopactionitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shopactionitem',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopactionitem',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopactionitem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_action_items', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý'),
        ),
        migrations.AddField(
            model_name='shopactionitem',
            name='source',
            field=models.CharField(choices=[('founder_insight', 'Founder Insight'), ('auto_freeze', 'Auto Freeze'), ('manual', 'Manual'), ('api', 'API')], default='founder_insight', max_length=32),
        ),
        migrations.AlterField(
            model_name='shopactionitem',
            name='status',
            field=models.CharField(choices=[('open', 'Mở'), ('doing', 'Đang làm'), ('blocked', 'Bị chặn'), ('done', 'Hoàn thành'), ('verified', 'Đã xác nhận')], default='open', max_length=20),
        ),
        migrations.AddIndex(
            model_name='shopactionitem',
            index=models.Index(fields=['severity'], name='idx_action_severity'),
        ),
        migrations.AddIndex(
            model_name='shopactionitem',
            index=models.Index(fields=['source'], name='idx_action_source'),
        ),
        migrations.AddIndex(
            model_name='shopactionitem',
            index=models.Index(fields=['due_at'], name='idx_action_due'),
        ),
    ]
