# Generated by Django 6.0.2 on 2026-02-16 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0004_shopactionitem_closed_at_shopactionitem_due_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shopactionitem',
            new_name='idx_action_sev',
            old_name='idx_action_severity',
        ),
        migrations.RenameIndex(
            model_name='shophealthsnapshot',
            new_name='idx_shsnap_month_risk',
            old_name='intelligenc_month_1d57ca_idx',
        ),
        migrations.RenameIndex(
            model_name='shophealthsnapshot',
            new_name='idx_shsnap_month_company',
            old_name='intelligenc_month_6819dd_idx',
        ),
        migrations.RenameIndex(
            model_name='shophealthsnapshot',
            new_name='idx_shsnap_month_shop',
            old_name='intelligenc_month_2bbdc9_idx',
        ),
        migrations.AlterField(
            model_name='shopactionitem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_shop_action_items', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý'),
        ),
        migrations.AlterField(
            model_name='shopactionitem',
            name='severity',
            field=models.CharField(choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2')], default='P1', max_length=10),
        ),
        migrations.AlterField(
            model_name='shopactionitem',
            name='source',
            field=models.CharField(choices=[('founder_insight', 'Founder Insight'), ('manual', 'Manual'), ('api', 'API')], db_index=True, default='founder_insight', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='shopactionitem',
            constraint=models.UniqueConstraint(fields=('month', 'shop_id', 'title', 'source'), name='uq_action_month_shop_title_source'),
        ),
    ]
