# Generated by Django 6.0.2 on 2026-02-18 10:19

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_alter_company_tenant'),
        ('shops', '0008_remove_shopmember_idx_shopmember_shop_and_more'),
        ('tenants', '0006_alter_tenant_options_alter_tenantdomain_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='shops.shop')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qty', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='booking.booking')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_items', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tenant', 'company'], name='idx_booking_tenant_company'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tenant', 'status'], name='idx_booking_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tenant', 'scheduled_at'], name='idx_booking_tenant_sched'),
        ),
        migrations.AddIndex(
            model_name='bookingitem',
            index=models.Index(fields=['tenant', 'booking'], name='idx_bitem_tenant_booking'),
        ),
    ]
