# Generated by Django 4.2.11 on 2026-03-08 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0002_contractpayment_total_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0010_remove_shopmember_uq_shopmember_shop_user_and_more'),
        ('companies', '0004_alter_company_unique_together_and_more'),
        ('tenants', '0009_tenant_suspended_at_alter_tenant_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopServiceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(choices=[('booking', 'Booking'), ('channel_build', 'Xây kênh'), ('livestream', 'Livestream'), ('operations', 'Vận hành'), ('ads', 'Ads'), ('koc', 'KOC'), ('content', 'Content'), ('other', 'Khác')], db_index=True, default='other', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('active', 'Đang dùng'), ('paused', 'Tạm dừng'), ('ended', 'Kết thúc'), ('cancelled', 'Huỷ')], db_index=True, default='draft', max_length=20)),
                ('service_name', models.CharField(blank=True, default='', help_text='Tên hiển thị dịch vụ nếu cần custom riêng', max_length=255)),
                ('start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_service_subscriptions', to='companies.company')),
                ('contract', models.ForeignKey(blank=True, help_text='Liên kết hợp đồng nếu dịch vụ này đi theo hợp đồng cụ thể', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_service_subscriptions', to='contracts.contract')),
                ('owner', models.ForeignKey(blank=True, help_text='Người phụ trách dịch vụ này', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_shop_services', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_subscriptions', to='shops.shop')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['shop_id', 'service_code', '-id'],
                'indexes': [models.Index(fields=['tenant', 'shop', 'status'], name='ssub_t_sh_st_idx'), models.Index(fields=['tenant', 'service_code', 'status'], name='ssub_t_sv_st_idx'), models.Index(fields=['tenant', 'start_date', 'end_date'], name='ssub_t_sd_ed_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='shopservicesubscription',
            constraint=models.UniqueConstraint(fields=('shop', 'service_code', 'contract'), name='uq_shop_service_contract'),
        ),
    ]
