# Generated by Django 4.2.11 on 2026-03-10 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255, verbose_name='Tên thương hiệu')),
                ('contract_start', models.DateField(verbose_name='Ngày bắt đầu hợp đồng')),
                ('contract_end', models.DateField(verbose_name='Ngày kết thúc hợp đồng')),
                ('fixed_fee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Phí cố định')),
                ('percent_fee', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Phần trăm phí (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('account_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clients', to=settings.AUTH_USER_MODEL, verbose_name='Account phụ trách')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='companies.company', verbose_name='Công ty')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_clients', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên vận hành')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'ordering': ['-created_at'],
            },
        ),
    ]
