# Generated by Django 4.2.11 on 2026-03-10 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('shopee', 'Shopee'), ('lazada', 'Lazada'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_channels', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ChannelAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, default='', max_length=255)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='channels.channel')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_accounts', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ChannelShopLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_links', to='channels.channel')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_links', to='shops.shop')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_shop_links', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'channel'], name='idx_chshop_tenant_channel'), models.Index(fields=['tenant', 'shop'], name='idx_chshop_tenant_shop')],
            },
        ),
        migrations.AddConstraint(
            model_name='channelshoplink',
            constraint=models.UniqueConstraint(fields=('tenant', 'channel', 'shop'), name='uq_channel_shop_link'),
        ),
        migrations.AddIndex(
            model_name='channelaccount',
            index=models.Index(fields=['tenant', 'channel'], name='idx_chacc_tenant_channel'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['tenant', 'company'], name='idx_channel_tenant_company'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['tenant', 'type'], name='idx_channel_tenant_type'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['tenant', 'is_active'], name='idx_channel_tenant_active'),
        ),
    ]
