# Generated by Django 4.2.11 on 2026-02-27 01:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuleDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('shop_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('industry_code', models.CharField(db_index=True, max_length=64)),
                ('rule_version', models.CharField(db_index=True, max_length=32)),
                ('rule_key', models.CharField(db_index=True, max_length=128)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('output_result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['industry_code', 'rule_version', 'rule_key', 'created_at'], name='rules_ruled_industr_fef16a_idx')],
            },
        ),
    ]
