# Generated by Django 4.2.11 on 2026-03-10 04:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuleDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('shop_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('industry_code', models.CharField(db_index=True, max_length=64)),
                ('rule_version', models.CharField(db_index=True, max_length=32)),
                ('rule_key', models.CharField(db_index=True, max_length=128)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('output_result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RuleRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_code', models.CharField(db_index=True, max_length=64)),
                ('rule_version', models.CharField(db_index=True, max_length=32)),
                ('effective_from', models.DateField(db_index=True)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['industry_code', 'rule_version', 'is_enabled', 'effective_from'], name='idx_rule_release')],
            },
        ),
        migrations.AddConstraint(
            model_name='rulerelease',
            constraint=models.UniqueConstraint(fields=('industry_code', 'rule_version', 'effective_from'), name='uq_rule_release_industry_version_effective'),
        ),
        migrations.AddIndex(
            model_name='ruledecisionlog',
            index=models.Index(fields=['industry_code', 'rule_version', 'rule_key', 'created_at'], name='rules_ruled_industr_fef16a_idx'),
        ),
    ]
