# Generated by Django 4.2.11 on 2026-02-27 01:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_code', models.CharField(db_index=True, max_length=64)),
                ('rule_version', models.CharField(db_index=True, max_length=32)),
                ('effective_from', models.DateField(db_index=True)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['industry_code', 'rule_version', 'is_enabled', 'effective_from'], name='idx_rule_release')],
            },
        ),
        migrations.AddConstraint(
            model_name='rulerelease',
            constraint=models.UniqueConstraint(fields=('industry_code', 'rule_version', 'effective_from'), name='uq_rule_release_industry_version_effective'),
        ),
    ]
