# Generated by Django 4.2.11 on 2026-03-10 04:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('tenants', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('user_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('level', models.CharField(choices=[('info', 'Thông tin'), ('warning', 'Cảnh báo'), ('critical', 'Khẩn cấp')], db_index=True, default='info', max_length=20)),
                ('status', models.CharField(choices=[('unread', 'Chưa đọc'), ('read', 'Đã đọc'), ('archived', 'Lưu trữ')], db_index=True, default='unread', max_length=20)),
                ('tieu_de', models.CharField(blank=True, default='', max_length=255)),
                ('noi_dung', models.TextField(blank=True, default='')),
                ('doi_tuong_loai', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('doi_tuong_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, default='', max_length=180)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.shop')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['tenant', 'status', 'created_at'], name='ntf_t_st_ct_idx'), models.Index(fields=['tenant', 'shop', 'status', 'created_at'], name='ntf_t_sh_st_ct_idx'), models.Index(fields=['tenant', 'user_id', 'status', 'created_at'], name='ntf_t_u_st_ct_idx'), models.Index(fields=['dedupe_key'], name='ntf_dedupe_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('dedupe_key',), name='uq_notification_dedupe_key'),
        ),
    ]
