# Generated by Django 4.2.11 on 2026-03-10 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
        ('projects', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_key', models.PositiveIntegerField(db_index=True, default=0)),
                ('visible_to_client', models.BooleanField(db_index=True, default=False)),
                ('type', models.CharField(choices=[('task', 'Task'), ('bug', 'Bug'), ('campaign', 'Campaign'), ('report', 'Report')], db_index=True, default='task', max_length=20)),
                ('target_type', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('doing', 'Doing'), ('blocked', 'Blocked'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='todo', max_length=20)),
                ('workflow_version', models.PositiveIntegerField(db_index=True, default=1, help_text='Workflow version frozen at creation time')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent')], db_index=True, default=2)),
                ('rank', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('position', models.PositiveIntegerField(db_index=True, default=1)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items_assigned', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items_requested', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='shops.shop')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_comments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='work.workitem')),
            ],
            options={
                'db_table': 'work_comment',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkItemTransitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('workflow_version', models.PositiveIntegerField(db_index=True, default=1)),
                ('reason', models.TextField(blank=True, default='')),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('trace_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('workitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_logs', to='work.workitem')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['tenant', 'company', 'project', 'workitem', 'created_at'], name='wlt_t_c_p_w_ct_idx'), models.Index(fields=['tenant', 'workflow_version', 'created_at'], name='wlt_t_wfv_ct_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'status'], name='wi_t_st_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'priority'], name='wi_t_pri_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'company'], name='wi_t_co_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'project'], name='wi_t_pj_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'target_type', 'target_id'], name='wi_t_tg_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'company', 'status', 'rank'], name='wi_t_c_sr_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'is_internal'], name='wi_t_int_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'workflow_version'], name='wi_t_wfv_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'shop'], name='wi_t_shop_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'shop', 'status', 'rank'], name='wi_t_shop_sr_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'shop', 'visible_to_client'], name='wi_t_shop_vtc_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'type'], name='wi_t_type_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'company_key', 'status', 'rank'], name='wi_t_ck_sr_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'assignee'], name='wi_t_asg_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'updated_at'], name='wi_t_upd_idx'),
        ),
        migrations.AddConstraint(
            model_name='workitem',
            constraint=models.UniqueConstraint(fields=('tenant', 'company_key', 'status', 'rank'), name='uq_wi_tenant_companykey_status_rank'),
        ),
        migrations.AddConstraint(
            model_name='workitem',
            constraint=models.CheckConstraint(check=models.Q(('position__gte', 1)), name='ck_wi_position_gte_1'),
        ),
        migrations.AddIndex(
            model_name='workcomment',
            index=models.Index(fields=['tenant', 'work_item'], name='wc_t_wi_idx'),
        ),
        migrations.AddIndex(
            model_name='workcomment',
            index=models.Index(fields=['tenant', 'created_at'], name='wc_t_ct_idx'),
        ),
    ]
