# Generated by Django 4.2.11 on 2026-03-12 06:16

import apps.work.models_attachment
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.BigIntegerField(db_index=True)),
                ('file', models.FileField(upload_to=apps.work.models_attachment.task_attachment_upload_to)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='work.workitem')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'work_task_attachment',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['tenant_id', 'task'], name='work_task_a_tenant__6ca321_idx'), models.Index(fields=['tenant_id', 'is_deleted'], name='work_task_a_tenant__971e31_idx')],
            },
        ),
    ]
