# Generated by Django 5.2.11 on 2026-02-21 22:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_unique_together_and_more'),
        ('projects', '0004_alter_project_status'),
        ('tenants', '0009_tenant_suspended_at_alter_tenant_status_and_more'),
        ('work', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'status', 'position'], name='wi_t_sp_idx'),
        ),
    ]
