# Generated by Django 4.2.11 on 2026-03-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_taskattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachment',
            name='company_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='project_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='shop_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='target_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='target_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='taskattachment',
            index=models.Index(fields=['tenant_id', 'shop_id'], name='work_task_a_tenant__9b74aa_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattachment',
            index=models.Index(fields=['tenant_id', 'project_id'], name='work_task_a_tenant__ba20dd_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattachment',
            index=models.Index(fields=['tenant_id', 'target_type', 'target_id'], name='work_task_a_tenant__e74bed_idx'),
        ),
    ]
