# Generated by Django 5.2.11 on 2026-02-23 01:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_unique_together_and_more'),
        ('projects', '0004_alter_project_status'),
        ('tenants', '0009_tenant_suspended_at_alter_tenant_status_and_more'),
        ('work', '0002_workitem_position_workitem_wi_t_sp_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='is_internal',
            field=models.BooleanField(db_index=True, default=False, help_text='Nếu bật: chỉ nội bộ thấy, khách hàng không thấy'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'is_internal'], name='wi_t_int_idx'),
        ),
    ]
