# Generated by Django 4.2.11 on 2026-02-27 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0004_alter_company_unique_together_and_more'),
        ('projects', '0005_alter_project_options_and_more'),
        ('tenants', '0009_tenant_suspended_at_alter_tenant_status_and_more'),
        ('work', '0003_workitem_is_internal_workitem_wi_t_int_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItemTransitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True, default='')),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('trace_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='workcomment',
            name='wc_t_wi_idx',
        ),
        migrations.RemoveIndex(
            model_name='workcomment',
            name='wc_t_ct_idx',
        ),
        migrations.RemoveIndex(
            model_name='workitem',
            name='wi_t_st_idx',
        ),
        migrations.RemoveIndex(
            model_name='workitem',
            name='wi_t_pri_idx',
        ),
        migrations.RemoveIndex(
            model_name='workitem',
            name='wi_t_co_idx',
        ),
        migrations.RemoveIndex(
            model_name='workitem',
            name='wi_t_pj_idx',
        ),
        migrations.RemoveIndex(
            model_name='workitem',
            name='wi_t_tg_idx',
        ),
        migrations.RemoveIndex(
            model_name='workitem',
            name='wi_t_as_st_idx',
        ),
        migrations.RemoveIndex(
            model_name='workitem',
            name='wi_t_sp_idx',
        ),
        migrations.RemoveIndex(
            model_name='workitem',
            name='wi_t_int_idx',
        ),
        migrations.RemoveField(
            model_name='workitem',
            name='tags',
        ),
        migrations.AlterField(
            model_name='workcomment',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workcomment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='is_internal',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workitemtransitionlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workitemtransitionlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='workitemtransitionlog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='workitemtransitionlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='workitemtransitionlog',
            name='workitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_logs', to='work.workitem'),
        ),
    ]
