# Generated by Django 4.2.11 on 2026-02-27 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_tenant_suspended_at_alter_tenant_status_and_more'),
        ('projects', '0005_alter_project_options_and_more'),
        ('companies', '0004_alter_company_unique_together_and_more'),
        ('work', '0004_workitemtransitionlog_remove_workcomment_wc_t_wi_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='workflow_version',
            field=models.PositiveIntegerField(db_index=True, default=1, help_text='Workflow version frozen at creation time'),
        ),
        migrations.AddField(
            model_name='workitemtransitionlog',
            name='workflow_version',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='workitemtransitionlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='workitemtransitionlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='workitemtransitionlog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='workcomment',
            index=models.Index(fields=['tenant', 'work_item'], name='wc_t_wi_idx'),
        ),
        migrations.AddIndex(
            model_name='workcomment',
            index=models.Index(fields=['tenant', 'created_at'], name='wc_t_ct_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'status'], name='wi_t_st_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'priority'], name='wi_t_pri_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'company'], name='wi_t_co_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'project'], name='wi_t_pj_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'target_type', 'target_id'], name='wi_t_tg_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'status', 'position'], name='wi_t_sp_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'is_internal'], name='wi_t_int_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'workflow_version'], name='wi_t_wfv_idx'),
        ),
        migrations.AddIndex(
            model_name='workitemtransitionlog',
            index=models.Index(fields=['tenant', 'company', 'project', 'workitem', 'created_at'], name='wlt_t_c_p_w_ct_idx'),
        ),
        migrations.AddIndex(
            model_name='workitemtransitionlog',
            index=models.Index(fields=['tenant', 'workflow_version', 'created_at'], name='wlt_t_wfv_ct_idx'),
        ),
    ]
