# Generated by Django 4.2.11 on 2026-02-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_workitem_position_unique'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workitem',
            name='wi_t_sp_idx',
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'company', 'status', 'position'], name='wi_t_c_sp_idx'),
        ),
    ]
