# Generated by Django 4.2.11 on 2026-02-27 15:04

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_remove_workitem_wi_t_sp_idx_workitem_wi_t_c_sp_idx'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workitem',
            name='uq_wi_tenant_company_status_pos',
        ),
        migrations.AddConstraint(
            model_name='workitem',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('tenant', 'company', 'status', 'position'), name='uq_wi_tenant_company_status_pos'),
        ),
        migrations.AddConstraint(
            model_name='workitem',
            constraint=models.CheckConstraint(check=models.Q(('position__gte', 1)), name='ck_wi_position_gte_1'),
        ),
    ]
