# Generated by Django 4.2.11 on 2026-02-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_work_rank'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workitem',
            name='uq_wi_tenant_company_status_rank',
        ),
        migrations.RemoveIndex(
            model_name='workitem',
            name='wi_t_c_sp_idx',
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'company', 'status', 'rank'], name='wi_t_c_sr_idx'),
        ),
        migrations.AddConstraint(
            model_name='workitem',
            constraint=models.UniqueConstraint(fields=('tenant', 'company', 'status', 'rank'), name='uq_wi_tenant_company_status_rank'),
        ),
    ]
