# Generated by Django 4.2.11 on 2026-02-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_remove_workitem_uq_wi_tenant_company_status_rank_and_more'),
    ]

    operations = [
    migrations.RunSQL(
        sql="ALTER TABLE work_workitem ALTER COLUMN rank DROP DEFAULT;",
        reverse_sql=migrations.RunSQL.noop,
    ),
]
