# Generated by Django 4.2.11 on 2026-02-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_drop_workitem_rank_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='rank',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
