# Generated by Django 4.2.11 on 2026-03-04 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_remove_shopmember_uq_shopmember_shop_user_and_more'),
        ('work', '0012_alter_workitem_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='type',
            field=models.CharField(choices=[('task', 'Task'), ('bug', 'Bug'), ('campaign', 'Campaign'), ('report', 'Report')], db_index=True, default='task', max_length=20),
        ),
        migrations.AddField(
            model_name='workitem',
            name='visible_to_client',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'shop'], name='wi_t_shop_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'shop', 'status', 'rank'], name='wi_t_shop_sr_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'shop', 'visible_to_client'], name='wi_t_shop_vtc_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'type'], name='wi_t_type_idx'),
        ),
    ]
