# Generated by Django 4.2.11 on 2026-03-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_workitem_shop_workitem_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workitem',
            name='uq_wi_tenant_company_status_rank',
        ),
        migrations.AddField(
            model_name='workitem',
            name='company_key',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tenant', 'company_key', 'status', 'rank'], name='wi_t_ck_sr_idx'),
        ),
        migrations.AddConstraint(
            model_name='workitem',
            constraint=models.UniqueConstraint(fields=('tenant', 'company_key', 'status', 'rank'), name='uq_wi_tenant_companykey_status_rank'),
        ),
    ]
