# Generated by Django 4.2.11 on 2026-03-08 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0014_remove_workitem_uq_wi_tenant_company_status_rank_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workcomment',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.RemoveIndex(
            model_name='workcomment',
            name='wc_t_wi_idx',
        ),
        migrations.RemoveIndex(
            model_name='workcomment',
            name='wc_t_ct_idx',
        ),
        migrations.AddField(
            model_name='workcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workcomment',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='workcomment',
            index=models.Index(fields=['tenant', 'work_item', 'created_at'], name='idx_wc_tenant_item_time'),
        ),
        migrations.AlterModelTable(
            name='workcomment',
            table='work_comment',
        ),
    ]
