# Generated by Django 4.2.11 on 2026-03-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0015_alter_workcomment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workcomment',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveIndex(
            model_name='workcomment',
            name='idx_wc_tenant_item_time',
        ),
        migrations.RemoveField(
            model_name='workcomment',
            name='updated_at',
        ),
        migrations.AddIndex(
            model_name='workcomment',
            index=models.Index(fields=['tenant', 'work_item'], name='wc_t_wi_idx'),
        ),
        migrations.AddIndex(
            model_name='workcomment',
            index=models.Index(fields=['tenant', 'created_at'], name='wc_t_ct_idx'),
        ),
    ]
